### ISSUE TITLE
Conflicts with AttributeRouting library

### ISSUE THREAD

**Issue by brantb** [hazzik/ReSharper.StringFormat#9]
[AttributeRouting](http://attributerouting.net/#defining-routes) is a library for ASP.NET MVC that lets you express routes using attributes on your action methods like so:

```
[GET("Details/{imageId:guid}")]
public ActionResult Details(Guid imageId)
{/*...*/}
```

You can probably see where this is going.

Anyway, with the StringFormat extension installed, R# shows warnings everywhere:

![image](https://f.cloud.github.com/assets/150953/1310237/63af54ee-31ed-11e3-8e42-b49b522d983a.png)

It would be great if there were some way to work around this. I suppose ignoring string literals as attribute parameters would do the trick, since `string.Format` isn't a legal expression there anyway.

**Comment by hazzik** [comment]
Thanks for the feedback.

**Comment by hazzik** [comment]
On nuget now.
